package dbms;
import java.text.SimpleDateFormat;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.JCheckBox;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rahulan
 */
public class seats extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public seats() {
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        datechooser = new com.toedter.calendar.JDateChooser();
        time = new javax.swing.JComboBox<>();
        type = new javax.swing.JComboBox<>();
        from = new javax.swing.JComboBox<>();
        des = new javax.swing.JComboBox<>();
        aid = new javax.swing.JTextField();
        btn_set = new javax.swing.JButton();
        btn_book = new javax.swing.JButton();
        chk1 = new javax.swing.JCheckBox();
        chk2 = new javax.swing.JCheckBox();
        chk5 = new javax.swing.JCheckBox();
        chk6 = new javax.swing.JCheckBox();
        chk9 = new javax.swing.JCheckBox();
        chk10 = new javax.swing.JCheckBox();
        chk13 = new javax.swing.JCheckBox();
        chk14 = new javax.swing.JCheckBox();
        chk17 = new javax.swing.JCheckBox();
        chk18 = new javax.swing.JCheckBox();
        chk21 = new javax.swing.JCheckBox();
        chk22 = new javax.swing.JCheckBox();
        chk25 = new javax.swing.JCheckBox();
        chk26 = new javax.swing.JCheckBox();
        chk29 = new javax.swing.JCheckBox();
        chk30 = new javax.swing.JCheckBox();
        chk33 = new javax.swing.JCheckBox();
        chk34 = new javax.swing.JCheckBox();
        chk37 = new javax.swing.JCheckBox();
        chk38 = new javax.swing.JCheckBox();
        chk41 = new javax.swing.JCheckBox();
        chk42 = new javax.swing.JCheckBox();
        chk15 = new javax.swing.JCheckBox();
        chk16 = new javax.swing.JCheckBox();
        chk19 = new javax.swing.JCheckBox();
        chk20 = new javax.swing.JCheckBox();
        chk23 = new javax.swing.JCheckBox();
        chk24 = new javax.swing.JCheckBox();
        chk27 = new javax.swing.JCheckBox();
        chk28 = new javax.swing.JCheckBox();
        chk31 = new javax.swing.JCheckBox();
        chk32 = new javax.swing.JCheckBox();
        chk35 = new javax.swing.JCheckBox();
        chk36 = new javax.swing.JCheckBox();
        chk39 = new javax.swing.JCheckBox();
        chk40 = new javax.swing.JCheckBox();
        chk43 = new javax.swing.JCheckBox();
        chk44 = new javax.swing.JCheckBox();
        chk3 = new javax.swing.JCheckBox();
        chk4 = new javax.swing.JCheckBox();
        chk7 = new javax.swing.JCheckBox();
        chk8 = new javax.swing.JCheckBox();
        chk11 = new javax.swing.JCheckBox();
        chk12 = new javax.swing.JCheckBox();
        jCheckBox47 = new javax.swing.JCheckBox();
        jCheckBox48 = new javax.swing.JCheckBox();
        chk45 = new javax.swing.JCheckBox();
        chk46 = new javax.swing.JCheckBox();
        jCheckBox51 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NIC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        getdown = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        gin = new javax.swing.JTextField();
        gintime = new javax.swing.JTextField();
        adrs = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        tno = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btn_chk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Boarding Date:");

        jLabel6.setText("Time:");

        jLabel7.setText("Type:");

        jLabel8.setText("To:");

        jLabel9.setText("From:");

        jLabel11.setText("Allocation ID:");

        time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "Night" }));
        time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeActionPerformed(evt);
            }
        });

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NAC" }));

        from.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jaffna", "Colombo" }));

        des.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colombo", "Jaffna" }));

        aid.setEditable(false);

        btn_set.setText("Set");
        btn_set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setActionPerformed(evt);
            }
        });

        btn_book.setText("Book Bus");
        btn_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookActionPerformed(evt);
            }
        });

        chk1.setText("01");

        chk2.setText("02");

        chk5.setText("05");

        chk6.setText("06");

        chk9.setText("09");

        chk10.setText("10");

        chk13.setText("13");

        chk14.setText("14");

        chk17.setText("17");

        chk18.setText("18");

        chk21.setText("21");

        chk22.setText("22");

        chk25.setText("25");

        chk26.setText("26");
        chk26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk26ActionPerformed(evt);
            }
        });

        chk29.setText("29");

        chk30.setText("30");

        chk33.setText("33");

        chk34.setText("34");

        chk37.setText("37");

        chk38.setText("38");

        chk41.setText("41");

        chk42.setText("42");

        chk15.setText("15");

        chk16.setText("16");
        chk16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk16ActionPerformed(evt);
            }
        });

        chk19.setText("19");

        chk20.setText("20");

        chk23.setText("23");

        chk24.setText("24");

        chk27.setText("27");

        chk28.setText("28");

        chk31.setText("31");

        chk32.setText("32");

        chk35.setText("35");

        chk36.setText("36");

        chk39.setText("39");

        chk40.setText("40");

        chk43.setText("43");

        chk44.setText("44");

        chk3.setText("03");

        chk4.setText("04");

        chk7.setText("07");

        chk8.setText("08");

        chk11.setText("11");

        chk12.setText("12");

        jCheckBox47.setText("48");

        jCheckBox48.setText("49");

        chk45.setText("45");

        chk46.setText("46");

        jCheckBox51.setText("47");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seat Order");

        jButton1.setText("Main menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("NIC_No:");

        jLabel4.setText("Name:");

        jLabel5.setText("Tel_No:");

        jLabel10.setText("Address:");

        jLabel12.setText("Gender:");

        jLabel13.setText("Get In:");

        jLabel14.setText("Get in Time:");

        jLabel15.setText("Destination:");

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        adrs.setEditable(false);

        name.setEditable(false);

        tno.setEditable(false);

        jButton2.setText("View Seats");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_chk.setText("Check");
        btn_chk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(429, 429, 429)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_chk))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(chk1)
                .addGap(3, 3, 3)
                .addComponent(chk2)
                .addGap(74, 74, 74)
                .addComponent(chk3)
                .addGap(2, 2, 2)
                .addComponent(chk4))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(chk5)
                .addGap(3, 3, 3)
                .addComponent(chk6)
                .addGap(74, 74, 74)
                .addComponent(chk7)
                .addGap(2, 2, 2)
                .addComponent(chk8))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(chk9)
                .addGap(3, 3, 3)
                .addComponent(chk10)
                .addGap(74, 74, 74)
                .addComponent(chk11)
                .addGap(2, 2, 2)
                .addComponent(chk12))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(chk13)
                .addGap(2, 2, 2)
                .addComponent(chk14)
                .addGap(73, 73, 73)
                .addComponent(chk15)
                .addGap(2, 2, 2)
                .addComponent(chk16))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(aid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btn_set)
                .addGap(73, 73, 73)
                .addComponent(chk17)
                .addGap(2, 2, 2)
                .addComponent(chk18)
                .addGap(73, 73, 73)
                .addComponent(chk19)
                .addGap(2, 2, 2)
                .addComponent(chk20))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(chk21)
                .addGap(2, 2, 2)
                .addComponent(chk22)
                .addGap(73, 73, 73)
                .addComponent(chk23)
                .addGap(2, 2, 2)
                .addComponent(chk24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(tno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(chk25)
                .addGap(2, 2, 2)
                .addComponent(chk26)
                .addGap(73, 73, 73)
                .addComponent(chk27)
                .addGap(2, 2, 2)
                .addComponent(chk28))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(adrs, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(chk29)
                .addGap(2, 2, 2)
                .addComponent(chk30)
                .addGap(73, 73, 73)
                .addComponent(chk31)
                .addGap(2, 2, 2)
                .addComponent(chk32))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(chk33)
                .addGap(2, 2, 2)
                .addComponent(chk34)
                .addGap(73, 73, 73)
                .addComponent(chk35)
                .addGap(2, 2, 2)
                .addComponent(chk36))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(gin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(chk37)
                .addGap(2, 2, 2)
                .addComponent(chk38)
                .addGap(73, 73, 73)
                .addComponent(chk39)
                .addGap(2, 2, 2)
                .addComponent(chk40))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(gintime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(chk41)
                .addGap(2, 2, 2)
                .addComponent(chk42)
                .addGap(73, 73, 73)
                .addComponent(chk43)
                .addGap(2, 2, 2)
                .addComponent(chk44))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(getdown, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(chk45)
                .addGap(2, 2, 2)
                .addComponent(chk46)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox51)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox47)
                .addGap(2, 2, 2)
                .addComponent(jCheckBox48))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jButton2)
                .addGap(43, 43, 43)
                .addComponent(btn_book, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chk))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3))
                    .addComponent(datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chk1)
                    .addComponent(chk2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(chk3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(chk4)))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(chk5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(chk6))
                    .addComponent(chk7)
                    .addComponent(chk8))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(chk9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(chk10))
                    .addComponent(chk11)
                    .addComponent(chk12))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(chk13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(chk14))
                    .addComponent(chk15)
                    .addComponent(chk16))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(aid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_set)
                    .addComponent(chk17)
                    .addComponent(chk18)
                    .addComponent(chk19)
                    .addComponent(chk20))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chk21)
                    .addComponent(chk22)
                    .addComponent(chk23)
                    .addComponent(chk24))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(tno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chk25)
                    .addComponent(chk26)
                    .addComponent(chk27)
                    .addComponent(chk28))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(adrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chk29)
                    .addComponent(chk30)
                    .addComponent(chk31)
                    .addComponent(chk32))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chk33)
                    .addComponent(chk34)
                    .addComponent(chk35)
                    .addComponent(chk36))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(gin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chk37)
                    .addComponent(chk38)
                    .addComponent(chk39)
                    .addComponent(chk40))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(gintime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chk41)
                    .addComponent(chk42)
                    .addComponent(chk43)
                    .addComponent(chk44))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel15))
                    .addComponent(getdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chk45)
                    .addComponent(chk46)
                    .addComponent(jCheckBox51)
                    .addComponent(jCheckBox47)
                    .addComponent(jCheckBox48))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton1))
                    .addComponent(jButton2)
                    .addComponent(btn_book))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean chk_field(){
    if(NIC.getText().isEmpty()||aid.getText().isEmpty()||name.getText().isEmpty()||tno.getText().isEmpty()||adrs.getText().isEmpty()||gender.getSelectedIndex()<=-1||gin.getText().isEmpty()||gintime.getText().isEmpty()||getdown.getText().isEmpty()){
    return false;
    }
        return true;
    }
    
    private void btn_setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setActionPerformed
       String stime=time.getSelectedItem().toString();
       String stype=type.getSelectedItem().toString();
       String sfrom=from.getSelectedItem().toString();
       String sdes=des.getSelectedItem().toString();
       
        
        if(stime=="Day" && stype=="AC" && sfrom=="Jaffna" && sdes=="Colombo")
       {
           aid.setText("JC-D-AC");
       }
        else  if(stime=="Day" && stype=="NAC" && sfrom=="Jaffna" && sdes=="Colombo")
       {
           aid.setText("JC-D-NAC");
       }
        else if(stime=="Night" && stype=="AC" && sfrom=="Jaffna" && sdes=="Colombo")
       {
           aid.setText("JC-N-AC");
       }
        else if(stime=="Night" && stype=="NAC" && sfrom=="Jaffna" && sdes=="Colombo")
       {
           aid.setText("JC-N-NAC");
       }
        else if(stime=="Day" && stype=="AC" && sfrom=="Colombo" && sdes=="Jaffna")
       {
           aid.setText("CJ-D-AC");
       }
        else if(stime=="Day" && stype=="NAC" && sfrom=="Colombo" && sdes=="Jaffna")
       {
           aid.setText("CJ-D-NAC");
       }
        else if(stime=="Night" && stype=="AC" && sfrom=="Colombo" && sdes=="Jaffna")
       {
           aid.setText("CJ-N-AC");
       }
        else if(stime=="Night" && stype=="NAC" && sfrom=="Colombo" && sdes=="Jaffna")
       {
           aid.setText("CJ-N-NAC");
       }
        else 
        {
         JOptionPane.showMessageDialog(null,"Invalid Selection!");
        }
        
            
       
    }//GEN-LAST:event_btn_setActionPerformed

    
    
    private void btn_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookActionPerformed
        
        boolean chk_chkb=false;
        
        ArrayList<JCheckBox> chk_seat=new ArrayList<>();
        chk_seat.add(chk1);
        chk_seat.add(chk2);
        chk_seat.add(chk3);
        chk_seat.add(chk4);
        chk_seat.add(chk5);
        chk_seat.add(chk6);
        chk_seat.add(chk7);
        chk_seat.add(chk8);
        chk_seat.add(chk9);
        chk_seat.add(chk10);
        chk_seat.add(chk11);
        chk_seat.add(chk12);
        chk_seat.add(chk13);
        chk_seat.add(chk14);
        chk_seat.add(chk15);
        chk_seat.add(chk16);
        chk_seat.add(chk17);
        chk_seat.add(chk18);
        chk_seat.add(chk19);
        chk_seat.add(chk20);
        chk_seat.add(chk21);
        chk_seat.add(chk22);
        chk_seat.add(chk23);
        chk_seat.add(chk24);
        chk_seat.add(chk25);
        chk_seat.add(chk26);
        chk_seat.add(chk27);
        chk_seat.add(chk28);
        chk_seat.add(chk29);
        chk_seat.add(chk30);
        chk_seat.add(chk31);
        chk_seat.add(chk32);
        chk_seat.add(chk33);
        chk_seat.add(chk34);
        chk_seat.add(chk35);
        chk_seat.add(chk36);
        chk_seat.add(chk37);
        chk_seat.add(chk38);
        chk_seat.add(chk39);
        chk_seat.add(chk40);
        chk_seat.add(chk41);
        chk_seat.add(chk42);
        chk_seat.add(chk43);
        chk_seat.add(chk44);
        chk_seat.add(chk45);
        chk_seat.add(chk46);
        chk_seat.add(jCheckBox51);
        chk_seat.add(jCheckBox47);
        chk_seat.add(jCheckBox48);
      
        ArrayList<JCheckBox> slt_seat=new ArrayList<>();
        for(JCheckBox chk:chk_seat){
        if(chk.isSelected()){
            slt_seat.add(chk);
                } 
            }
        
         for(JCheckBox chk:chk_seat){
         if(chk.isSelected()){
         chk_chkb=true;
         }
         }
        
        
        myconnection my=new myconnection();
         String date;
         String ic;
         String said=aid.getText();
         SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
         date=sdf.format(datechooser.getDate());
         ic=NIC.getText();
         
       
      
       try{
           if(chk_field()&&chk_chkb){
            for(JCheckBox chk:slt_seat){
                    String s_seat=chk.getText();
                    int t_no=Integer.parseInt(tno.getText());
                    Connection conn=my.getDBConnection();
                    PreparedStatement ps;
                    String sql3="INSERT INTO code_stars.booking_info2(NIC_no,Allocation_ID,Seat_Id,Date,Time,Place,Destination) values('"+ic+"'"
                            + ",'"+said+"','"+s_seat+"','"+date+"','"+gintime.getText()+"','"+gin.getText()+"','"+getdown.getText()+"')";
                     String sql="INSERT INTO code_stars.seat_allocation(Boarding_Date,Allocation_ID,Seat_ID) values('"+date+"','"+said+"','"+s_seat+"')";
                     ps=conn.prepareStatement(sql3);                   
                    ps.executeUpdate(sql3);
                      ps=conn.prepareStatement(sql);
                    ps.executeUpdate(sql);
           }
             JOptionPane.showMessageDialog(null,"Successfully Seat Booked");
                    
            }else{
            JOptionPane.showMessageDialog(null,"Empty Fields");
           }
           
          
       }
       catch(NumberFormatException ex){
           JOptionPane.showMessageDialog(null, ex);
       }
       catch(SQLException ex){
           JOptionPane.showMessageDialog(null, ex);
           
       }
       
       
    }//GEN-LAST:event_btn_bookActionPerformed

    private void chk16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk16ActionPerformed

    private void chk26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk26ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Mainmenuform mn=new Mainmenuform();
        this.dispose();
        mn.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       viewseats vs=new viewseats();
       this.dispose();
       vs.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_chkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chkActionPerformed
      
        boolean chk_nic=false;
        myconnection my=new myconnection();
         PreparedStatement ps;
         Connection conn;
         ResultSet rs;
         
         try{
         conn=my.getDBConnection();
         String sql="SELECT NIC_no FROM code_stars.customer_info";
         ps=conn.prepareStatement(sql);
         rs=ps.executeQuery(sql);
         while(rs.next()){
             if(rs.getString("NIC_no").contentEquals(NIC.getText())){
             chk_nic=true;
             }
         }
         }catch(SQLException ex){
             JOptionPane.showMessageDialog(null, ex);
         }
         
         
         if(chk_nic){
         try{
         conn=my.getDBConnection();
         String sql="SELECT * FROM code_stars.customer_info WHERE NIC_no='"+NIC.getText()+"'";
         ps=conn.prepareStatement(sql);
         rs=ps.executeQuery(sql);
         while(rs.next()){
             name.setText(rs.getString("Name"));
             tno.setText(Integer.toString(rs.getInt("Tel_no")));
             adrs.setText(rs.getString("Address"));
             if(rs.getString("Gender").contentEquals("Male")){
             gender.setSelectedIndex(0);
             }else{
             gender.setSelectedIndex(1);
             }
             }
         }catch(SQLException e){
                JOptionPane.showMessageDialog(null, e); 
                 }
         }else{
             customerdetail cu=new customerdetail();
             this.dispose();
             cu.setVisible(true);
         }
    }//GEN-LAST:event_btn_chkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NIC;
    private javax.swing.JTextField adrs;
    private javax.swing.JTextField aid;
    private javax.swing.JButton btn_book;
    private javax.swing.JButton btn_chk;
    private javax.swing.JButton btn_set;
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk10;
    private javax.swing.JCheckBox chk11;
    private javax.swing.JCheckBox chk12;
    private javax.swing.JCheckBox chk13;
    private javax.swing.JCheckBox chk14;
    private javax.swing.JCheckBox chk15;
    private javax.swing.JCheckBox chk16;
    private javax.swing.JCheckBox chk17;
    private javax.swing.JCheckBox chk18;
    private javax.swing.JCheckBox chk19;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JCheckBox chk20;
    private javax.swing.JCheckBox chk21;
    private javax.swing.JCheckBox chk22;
    private javax.swing.JCheckBox chk23;
    private javax.swing.JCheckBox chk24;
    private javax.swing.JCheckBox chk25;
    private javax.swing.JCheckBox chk26;
    private javax.swing.JCheckBox chk27;
    private javax.swing.JCheckBox chk28;
    private javax.swing.JCheckBox chk29;
    private javax.swing.JCheckBox chk3;
    private javax.swing.JCheckBox chk30;
    private javax.swing.JCheckBox chk31;
    private javax.swing.JCheckBox chk32;
    private javax.swing.JCheckBox chk33;
    private javax.swing.JCheckBox chk34;
    private javax.swing.JCheckBox chk35;
    private javax.swing.JCheckBox chk36;
    private javax.swing.JCheckBox chk37;
    private javax.swing.JCheckBox chk38;
    private javax.swing.JCheckBox chk39;
    private javax.swing.JCheckBox chk4;
    private javax.swing.JCheckBox chk40;
    private javax.swing.JCheckBox chk41;
    private javax.swing.JCheckBox chk42;
    private javax.swing.JCheckBox chk43;
    private javax.swing.JCheckBox chk44;
    private javax.swing.JCheckBox chk45;
    private javax.swing.JCheckBox chk46;
    private javax.swing.JCheckBox chk5;
    private javax.swing.JCheckBox chk6;
    private javax.swing.JCheckBox chk7;
    private javax.swing.JCheckBox chk8;
    private javax.swing.JCheckBox chk9;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.swing.JComboBox<String> des;
    private javax.swing.JComboBox<String> from;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField getdown;
    private javax.swing.JTextField gin;
    private javax.swing.JTextField gintime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox47;
    private javax.swing.JCheckBox jCheckBox48;
    private javax.swing.JCheckBox jCheckBox51;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> time;
    private javax.swing.JTextField tno;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
