/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Rahulan
 */
public class update extends javax.swing.JFrame {

    /**
     * Creates new form details
     */
    public update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_view = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        datechooser = new com.toedter.calendar.JDateChooser();
        chk1 = new javax.swing.JCheckBox();
        chk2 = new javax.swing.JCheckBox();
        chk6 = new javax.swing.JCheckBox();
        chk5 = new javax.swing.JCheckBox();
        chk10 = new javax.swing.JCheckBox();
        chk9 = new javax.swing.JCheckBox();
        chk14 = new javax.swing.JCheckBox();
        chk13 = new javax.swing.JCheckBox();
        chk18 = new javax.swing.JCheckBox();
        chk17 = new javax.swing.JCheckBox();
        chk22 = new javax.swing.JCheckBox();
        chk21 = new javax.swing.JCheckBox();
        chk26 = new javax.swing.JCheckBox();
        chk25 = new javax.swing.JCheckBox();
        chk30 = new javax.swing.JCheckBox();
        chk29 = new javax.swing.JCheckBox();
        chk34 = new javax.swing.JCheckBox();
        chk33 = new javax.swing.JCheckBox();
        chk38 = new javax.swing.JCheckBox();
        chk37 = new javax.swing.JCheckBox();
        chk42 = new javax.swing.JCheckBox();
        chk41 = new javax.swing.JCheckBox();
        chk46 = new javax.swing.JCheckBox();
        chk45 = new javax.swing.JCheckBox();
        chk20 = new javax.swing.JCheckBox();
        chk15 = new javax.swing.JCheckBox();
        chk16 = new javax.swing.JCheckBox();
        chk11 = new javax.swing.JCheckBox();
        chk28 = new javax.swing.JCheckBox();
        chk23 = new javax.swing.JCheckBox();
        chk24 = new javax.swing.JCheckBox();
        chk19 = new javax.swing.JCheckBox();
        chk40 = new javax.swing.JCheckBox();
        chk35 = new javax.swing.JCheckBox();
        chk36 = new javax.swing.JCheckBox();
        chk31 = new javax.swing.JCheckBox();
        chk32 = new javax.swing.JCheckBox();
        chk27 = new javax.swing.JCheckBox();
        chk48 = new javax.swing.JCheckBox();
        chk49 = new javax.swing.JCheckBox();
        chk43 = new javax.swing.JCheckBox();
        chk44 = new javax.swing.JCheckBox();
        chk39 = new javax.swing.JCheckBox();
        chk12 = new javax.swing.JCheckBox();
        chk7 = new javax.swing.JCheckBox();
        chk8 = new javax.swing.JCheckBox();
        chk4 = new javax.swing.JCheckBox();
        chk3 = new javax.swing.JCheckBox();
        chk47 = new javax.swing.JCheckBox();
        aid = new javax.swing.JComboBox<>();
        combo_seat = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Seat Details");

        jLabel2.setText("NIC No:");

        jLabel3.setText("Allocation ID:");

        jLabel4.setText("Date");

        btn_view.setText("View");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });

        jButton4.setText("Main menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        chk1.setText("01");

        chk2.setText("02");

        chk6.setText("06");

        chk5.setText("05");

        chk10.setText("10");

        chk9.setText("09");

        chk14.setText("14");

        chk13.setText("13");

        chk18.setText("18");

        chk17.setText("17");

        chk22.setText("22");

        chk21.setText("21");

        chk26.setText("26");

        chk25.setText("25");

        chk30.setText("30");

        chk29.setText("29");

        chk34.setText("34");

        chk33.setText("33");

        chk38.setText("38");

        chk37.setText("37");

        chk42.setText("42");

        chk41.setText("41");

        chk46.setText("46");

        chk45.setText("45");

        chk20.setText("20");

        chk15.setText("15");

        chk16.setText("16");

        chk11.setText("11");

        chk28.setText("28");

        chk23.setText("23");

        chk24.setText("24");

        chk19.setText("19");

        chk40.setText("40");

        chk35.setText("35");

        chk36.setText("36");

        chk31.setText("31");

        chk32.setText("32");

        chk27.setText("27");

        chk48.setText("48");

        chk49.setText("49");

        chk43.setText("43");

        chk44.setText("44");

        chk39.setText("39");

        chk12.setText("12");

        chk7.setText("07");

        chk8.setText("08");
        chk8.setToolTipText("");

        chk4.setText("04");

        chk3.setText("03");

        chk47.setText("47");

        aid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JC-D-AC", "JC-D-NAC", "JC-N-AC", "JC-N-NAC", "CJ-D-AC", "CJ-D-NAC", "CJ-N-AC", "CJ-N-NAC" }));

        jLabel5.setText("Seat_ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(chk45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btn_view, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(combo_seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(aid, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(datechooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txt_nic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk42))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk38))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk34))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk26))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk18)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chk48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk49))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(chk43)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chk44))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(chk39)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chk40))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(chk35)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chk36))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(chk31)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chk32))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(chk27)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chk28))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(chk23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chk24))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(chk3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chk4))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(chk7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chk8))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(chk11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chk12))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(chk15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chk16))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(chk19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(chk20))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(aid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_view)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo_seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk3)
                                    .addComponent(chk4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk7)
                                    .addComponent(chk8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk11)
                                    .addComponent(chk12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk15)
                                    .addComponent(chk16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk19)
                                    .addComponent(chk20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk23)
                                    .addComponent(chk24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk27)
                                    .addComponent(chk28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk31)
                                    .addComponent(chk32))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk35)
                                    .addComponent(chk36))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk39)
                                    .addComponent(chk40))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk43)
                                    .addComponent(chk44))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk48)
                                    .addComponent(chk49)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk1)
                                    .addComponent(chk2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk5)
                                    .addComponent(chk6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk9)
                                    .addComponent(chk10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk13)
                                    .addComponent(chk14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk17)
                                    .addComponent(chk18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk21)
                                    .addComponent(chk22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk25)
                                    .addComponent(chk26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk29)
                                    .addComponent(chk30))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk33)
                                    .addComponent(chk34))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk37)
                                    .addComponent(chk38))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk41)
                                    .addComponent(chk42))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk45)
                                    .addComponent(chk46)
                                    .addComponent(chk47))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_delete)
                            .addComponent(jButton4))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Mainmenuform mn=new Mainmenuform();
        this.dispose();
        mn.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
 ArrayList<JCheckBox> chk_seat=new ArrayList<>();
        chk_seat.add(chk1);
        chk_seat.add(chk2);
        chk_seat.add(chk3);
        chk_seat.add(chk4);
        chk_seat.add(chk5);
        chk_seat.add(chk6);
        chk_seat.add(chk7);
        chk_seat.add(chk8);
        chk_seat.add(chk9);
        chk_seat.add(chk10);
        chk_seat.add(chk11);
        chk_seat.add(chk12);
        chk_seat.add(chk13);
        chk_seat.add(chk14);
        chk_seat.add(chk15);
        chk_seat.add(chk16);
        chk_seat.add(chk17);
        chk_seat.add(chk18);
        chk_seat.add(chk19);
        chk_seat.add(chk20);
        chk_seat.add(chk21);
        chk_seat.add(chk22);
        chk_seat.add(chk23);
        chk_seat.add(chk24);
        chk_seat.add(chk25);
        chk_seat.add(chk26);
        chk_seat.add(chk27);
        chk_seat.add(chk28);
        chk_seat.add(chk29);
        chk_seat.add(chk30);
        chk_seat.add(chk31);
        chk_seat.add(chk32);
        chk_seat.add(chk33);
        chk_seat.add(chk34);
        chk_seat.add(chk35);
        chk_seat.add(chk36);
        chk_seat.add(chk37);
        chk_seat.add(chk38);
        chk_seat.add(chk39);
        chk_seat.add(chk40);
        chk_seat.add(chk41);
        chk_seat.add(chk42);
        chk_seat.add(chk43);
        chk_seat.add(chk44);
        chk_seat.add(chk45);
        chk_seat.add(chk46);
        chk_seat.add(chk47);
        chk_seat.add(chk48);
        chk_seat.add(chk49); 
        
        combo_seat.removeAllItems();
        
        for(JCheckBox chk:chk_seat){
                chk.setSelected(false);
        }
        
        myconnection my=new myconnection();
        PreparedStatement ps;
        ResultSet rs;
        String nic=txt_nic.getText();
        String said=aid.getSelectedItem().toString();
         SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
         String date=sdf.format(datechooser.getDate());
        
        try{
            Connection conn=my.getDBConnection();
            String sql="SELECT Seat_ID FROM code_stars.booking_info2 WHERE NIC_no='"+nic+"' AND Allocation_ID='"+said+"' AND Date='"+date+"'";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery(sql);
                    
            
             while(rs.next()){
                 for(JCheckBox chk:chk_seat){
                 if(rs.getString("Seat_ID").contentEquals(chk.getText())){
             chk.setSelected(true);
             combo_seat.addItem(chk.getText());
             }
                 
                 }
             }
           
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }  
    
    private void btn_vseatsActionPerformed(java.awt.event.ActionEvent evt) {                                           
        viewseats vs=new viewseats();
       vs.setVisible(true);}
    
        private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {                                           
       myconnection my=new myconnection();
        PreparedStatement ps;
        
        
        String nic=txt_nic.getText();
        String said=aid.getSelectedItem().toString();
        String sid=combo_seat.getSelectedItem().toString();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
         String date=sdf.format(datechooser.getDate());
        
        try{
           Connection conn=my.getDBConnection();
        String sql="DELETE FROM code_stars.booking_info2 WHERE NIC_no='"+nic+"' AND Allocation_ID='"+said+"' AND Date='"+date+"' AND Seat_Id='"+sid+"'";
        ps= conn.prepareStatement(sql);
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "Successfully Deleted");
        }catch(SQLException e){
        JOptionPane.showMessageDialog(null, e);
        }
        
    }                 

    /**
    }//GEN-LAST:event_btn_viewActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For update see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aid;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_view;
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk10;
    private javax.swing.JCheckBox chk11;
    private javax.swing.JCheckBox chk12;
    private javax.swing.JCheckBox chk13;
    private javax.swing.JCheckBox chk14;
    private javax.swing.JCheckBox chk15;
    private javax.swing.JCheckBox chk16;
    private javax.swing.JCheckBox chk17;
    private javax.swing.JCheckBox chk18;
    private javax.swing.JCheckBox chk19;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JCheckBox chk20;
    private javax.swing.JCheckBox chk21;
    private javax.swing.JCheckBox chk22;
    private javax.swing.JCheckBox chk23;
    private javax.swing.JCheckBox chk24;
    private javax.swing.JCheckBox chk25;
    private javax.swing.JCheckBox chk26;
    private javax.swing.JCheckBox chk27;
    private javax.swing.JCheckBox chk28;
    private javax.swing.JCheckBox chk29;
    private javax.swing.JCheckBox chk3;
    private javax.swing.JCheckBox chk30;
    private javax.swing.JCheckBox chk31;
    private javax.swing.JCheckBox chk32;
    private javax.swing.JCheckBox chk33;
    private javax.swing.JCheckBox chk34;
    private javax.swing.JCheckBox chk35;
    private javax.swing.JCheckBox chk36;
    private javax.swing.JCheckBox chk37;
    private javax.swing.JCheckBox chk38;
    private javax.swing.JCheckBox chk39;
    private javax.swing.JCheckBox chk4;
    private javax.swing.JCheckBox chk40;
    private javax.swing.JCheckBox chk41;
    private javax.swing.JCheckBox chk42;
    private javax.swing.JCheckBox chk43;
    private javax.swing.JCheckBox chk44;
    private javax.swing.JCheckBox chk45;
    private javax.swing.JCheckBox chk46;
    private javax.swing.JCheckBox chk47;
    private javax.swing.JCheckBox chk48;
    private javax.swing.JCheckBox chk49;
    private javax.swing.JCheckBox chk5;
    private javax.swing.JCheckBox chk6;
    private javax.swing.JCheckBox chk7;
    private javax.swing.JCheckBox chk8;
    private javax.swing.JCheckBox chk9;
    private javax.swing.JComboBox<String> combo_seat;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_nic;
    // End of variables declaration//GEN-END:variables
}
