package dbms;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rahulan
 */
public class viewseats extends javax.swing.JFrame {

    /**
     * Creates new form details
     */
    public viewseats() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        chk1 = new javax.swing.JCheckBox();
        chk2 = new javax.swing.JCheckBox();
        chk5 = new javax.swing.JCheckBox();
        chk6 = new javax.swing.JCheckBox();
        chk9 = new javax.swing.JCheckBox();
        chk10 = new javax.swing.JCheckBox();
        chk13 = new javax.swing.JCheckBox();
        chk14 = new javax.swing.JCheckBox();
        chk17 = new javax.swing.JCheckBox();
        chk18 = new javax.swing.JCheckBox();
        chk21 = new javax.swing.JCheckBox();
        chk22 = new javax.swing.JCheckBox();
        chk25 = new javax.swing.JCheckBox();
        chk26 = new javax.swing.JCheckBox();
        chk29 = new javax.swing.JCheckBox();
        chk30 = new javax.swing.JCheckBox();
        chk33 = new javax.swing.JCheckBox();
        chk34 = new javax.swing.JCheckBox();
        chk37 = new javax.swing.JCheckBox();
        chk38 = new javax.swing.JCheckBox();
        chk41 = new javax.swing.JCheckBox();
        chk42 = new javax.swing.JCheckBox();
        chk45 = new javax.swing.JCheckBox();
        chk46 = new javax.swing.JCheckBox();
        chk16 = new javax.swing.JCheckBox();
        chk19 = new javax.swing.JCheckBox();
        chk20 = new javax.swing.JCheckBox();
        chk23 = new javax.swing.JCheckBox();
        chk24 = new javax.swing.JCheckBox();
        chk27 = new javax.swing.JCheckBox();
        chk28 = new javax.swing.JCheckBox();
        chk31 = new javax.swing.JCheckBox();
        chk32 = new javax.swing.JCheckBox();
        chk35 = new javax.swing.JCheckBox();
        chk36 = new javax.swing.JCheckBox();
        chk39 = new javax.swing.JCheckBox();
        chk40 = new javax.swing.JCheckBox();
        chk3 = new javax.swing.JCheckBox();
        chk4 = new javax.swing.JCheckBox();
        chk7 = new javax.swing.JCheckBox();
        chk43 = new javax.swing.JCheckBox();
        chk8 = new javax.swing.JCheckBox();
        chk44 = new javax.swing.JCheckBox();
        chk48 = new javax.swing.JCheckBox();
        chk49 = new javax.swing.JCheckBox();
        chk11 = new javax.swing.JCheckBox();
        chk12 = new javax.swing.JCheckBox();
        chk15 = new javax.swing.JCheckBox();
        chk47 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        datechooser = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        aid = new javax.swing.JComboBox<>();
        view = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jCheckBox5.setText("01");

        jCheckBox6.setText("02");

        jCheckBox23.setText("01");

        jCheckBox24.setText("02");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chk1.setText("01");

        chk2.setText("02");

        chk5.setText("05");

        chk6.setText("06");

        chk9.setText("09");

        chk10.setText("10");

        chk13.setText("13");

        chk14.setText("14");

        chk17.setText("17");

        chk18.setText("18");

        chk21.setText("21");

        chk22.setText("22");

        chk25.setText("25");

        chk26.setText("26");

        chk29.setText("29");

        chk30.setText("30");

        chk33.setText("33");

        chk34.setText("34");

        chk37.setText("37");

        chk38.setText("38");

        chk41.setText("41");

        chk42.setText("42");

        chk45.setText("45");

        chk46.setText("46");

        chk16.setText("16");

        chk19.setText("19");

        chk20.setText("20");

        chk23.setText("23");

        chk24.setText("24");

        chk27.setText("27");

        chk28.setText("28");

        chk31.setText("31");

        chk32.setText("32");

        chk35.setText("35");

        chk36.setText("36");

        chk39.setText("39");

        chk40.setText("40");

        chk3.setText("03");

        chk4.setText("04");

        chk7.setText("07");

        chk43.setText("43");

        chk8.setText("08");

        chk44.setText("44");

        chk48.setText("48");

        chk49.setText("49");

        chk11.setText("11");

        chk12.setText("12");

        chk15.setText("15");

        chk47.setText("47");

        jLabel1.setText("Boarding Date:");

        jLabel2.setText("Allocation ID:");

        aid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JC-D-AC", "JC-D-NAC", "JC-N-AC", "JC-N-NAC", "CJ-D-AC", "CJ-D-NAC", "CJ-N-AC", "CJ-N-NAC" }));

        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(datechooser, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(aid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(view)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chk5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chk6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chk1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chk2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk42))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk38))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk34))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk30))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(chk25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(chk26))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chk21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(chk22))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(chk17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(chk18))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(chk13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(chk14))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(chk9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(chk10))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk46)))
                        .addGap(18, 18, 18)
                        .addComponent(chk47)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chk48)
                    .addComponent(chk43)
                    .addComponent(chk39)
                    .addComponent(chk35)
                    .addComponent(chk31)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(chk27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chk23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(chk19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chk15)
                                    .addComponent(chk11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chk7)
                                    .addComponent(chk3))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chk49, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chk44, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chk40, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chk36, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chk32, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chk28, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chk24, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chk20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chk16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chk12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chk8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chk4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datechooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(aid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(view)
                            .addComponent(jButton1))
                        .addGap(348, 348, 348))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk3)
                                .addGap(18, 18, 18)
                                .addComponent(chk7)
                                .addGap(18, 18, 18)
                                .addComponent(chk11)
                                .addGap(18, 18, 18)
                                .addComponent(chk15)
                                .addGap(18, 18, 18)
                                .addComponent(chk19)
                                .addGap(18, 18, 18)
                                .addComponent(chk23)
                                .addGap(18, 18, 18)
                                .addComponent(chk27)
                                .addGap(18, 18, 18)
                                .addComponent(chk31)
                                .addGap(18, 18, 18)
                                .addComponent(chk35)
                                .addGap(18, 18, 18)
                                .addComponent(chk39)
                                .addGap(18, 18, 18)
                                .addComponent(chk43)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk48)
                                    .addComponent(chk47)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chk4)
                                .addGap(18, 18, 18)
                                .addComponent(chk8)
                                .addGap(18, 18, 18)
                                .addComponent(chk12)
                                .addGap(18, 18, 18)
                                .addComponent(chk16)
                                .addGap(18, 18, 18)
                                .addComponent(chk20)
                                .addGap(18, 18, 18)
                                .addComponent(chk24)
                                .addGap(18, 18, 18)
                                .addComponent(chk28)
                                .addGap(18, 18, 18)
                                .addComponent(chk32)
                                .addGap(18, 18, 18)
                                .addComponent(chk36)
                                .addGap(18, 18, 18)
                                .addComponent(chk40)
                                .addGap(18, 18, 18)
                                .addComponent(chk44)
                                .addGap(18, 18, 18)
                                .addComponent(chk49))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk1)
                                    .addComponent(chk2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk5)
                                    .addComponent(chk6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk9)
                                    .addComponent(chk10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk13)
                                    .addComponent(chk14))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk17)
                                    .addComponent(chk18))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk21)
                                    .addComponent(chk22))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk25)
                                    .addComponent(chk26))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk29)
                                    .addComponent(chk30))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk33)
                                    .addComponent(chk34))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk37)
                                    .addComponent(chk38))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk41)
                                    .addComponent(chk42))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chk45)
                                    .addComponent(chk46))))
                        .addGap(0, 33, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        ArrayList<JCheckBox> chk_seat=new ArrayList<>();
        chk_seat.add(chk1);
        chk_seat.add(chk2);
        chk_seat.add(chk3);
        chk_seat.add(chk4);
        chk_seat.add(chk5);
        chk_seat.add(chk6);
        chk_seat.add(chk7);
        chk_seat.add(chk8);
        chk_seat.add(chk9);
        chk_seat.add(chk10);
        chk_seat.add(chk11);
        chk_seat.add(chk12);
        chk_seat.add(chk13);
        chk_seat.add(chk14);
        chk_seat.add(chk15);
        chk_seat.add(chk16);
        chk_seat.add(chk17);
        chk_seat.add(chk18);
        chk_seat.add(chk19);
        chk_seat.add(chk20);
        chk_seat.add(chk21);
        chk_seat.add(chk22);
        chk_seat.add(chk23);
        chk_seat.add(chk24);
        chk_seat.add(chk25);
        chk_seat.add(chk26);
        chk_seat.add(chk27);
        chk_seat.add(chk28);
        chk_seat.add(chk29);
        chk_seat.add(chk30);
        chk_seat.add(chk31);
        chk_seat.add(chk32);
        chk_seat.add(chk33);
        chk_seat.add(chk34);
        chk_seat.add(chk35);
        chk_seat.add(chk36);
        chk_seat.add(chk37);
        chk_seat.add(chk38);
        chk_seat.add(chk39);
        chk_seat.add(chk40);
        chk_seat.add(chk41);
        chk_seat.add(chk42);
        chk_seat.add(chk43);
        chk_seat.add(chk44);
        chk_seat.add(chk45);
        chk_seat.add(chk46);
        chk_seat.add(chk47);
        chk_seat.add(chk48);
        chk_seat.add(chk49);
        
        for(JCheckBox chk:chk_seat){
             chk.setSelected(false);
             }
        
        myconnection my=new myconnection();
        Connection conn=my.getDBConnection();
        PreparedStatement ps;
        ResultSet rs;
        String said=aid.getSelectedItem().toString();
         SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
         String date=sdf.format(datechooser.getDate());
        
        try{
            String sql="SELECT * FROM code_stars.booking_info2 WHERE Allocation_ID='"+said+"' AND Date='"+date+"'";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery(sql);
                    
            
             while(rs.next()){
                 for(JCheckBox chk:chk_seat){
                 if(rs.getString("Seat_ID").contentEquals(chk.getText())){
             chk.setSelected(true);
             }
                 
                 }
             }
           
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_viewActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        seats seat=new seats();
        this.dispose();
        seat.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For viewseats see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewseats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewseats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewseats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewseats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewseats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aid;
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk10;
    private javax.swing.JCheckBox chk11;
    private javax.swing.JCheckBox chk12;
    private javax.swing.JCheckBox chk13;
    private javax.swing.JCheckBox chk14;
    private javax.swing.JCheckBox chk15;
    private javax.swing.JCheckBox chk16;
    private javax.swing.JCheckBox chk17;
    private javax.swing.JCheckBox chk18;
    private javax.swing.JCheckBox chk19;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JCheckBox chk20;
    private javax.swing.JCheckBox chk21;
    private javax.swing.JCheckBox chk22;
    private javax.swing.JCheckBox chk23;
    private javax.swing.JCheckBox chk24;
    private javax.swing.JCheckBox chk25;
    private javax.swing.JCheckBox chk26;
    private javax.swing.JCheckBox chk27;
    private javax.swing.JCheckBox chk28;
    private javax.swing.JCheckBox chk29;
    private javax.swing.JCheckBox chk3;
    private javax.swing.JCheckBox chk30;
    private javax.swing.JCheckBox chk31;
    private javax.swing.JCheckBox chk32;
    private javax.swing.JCheckBox chk33;
    private javax.swing.JCheckBox chk34;
    private javax.swing.JCheckBox chk35;
    private javax.swing.JCheckBox chk36;
    private javax.swing.JCheckBox chk37;
    private javax.swing.JCheckBox chk38;
    private javax.swing.JCheckBox chk39;
    private javax.swing.JCheckBox chk4;
    private javax.swing.JCheckBox chk40;
    private javax.swing.JCheckBox chk41;
    private javax.swing.JCheckBox chk42;
    private javax.swing.JCheckBox chk43;
    private javax.swing.JCheckBox chk44;
    private javax.swing.JCheckBox chk45;
    private javax.swing.JCheckBox chk46;
    private javax.swing.JCheckBox chk47;
    private javax.swing.JCheckBox chk48;
    private javax.swing.JCheckBox chk49;
    private javax.swing.JCheckBox chk5;
    private javax.swing.JCheckBox chk6;
    private javax.swing.JCheckBox chk7;
    private javax.swing.JCheckBox chk8;
    private javax.swing.JCheckBox chk9;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
